import sys
import time

a = 4
b = 0.05
c = 0.02



def intro():
    print()
    time.sleep(2)
    print("Everything around you looks bright yellow, cold, empty and liverish... The atmosphere is oddly hot, and suffocating...")
    time.sleep(3)
    print("You abruptly fall... face plant on a beige nasty, wet carpet. The moist of the rug cancelles out the huge noise. The place in which you have fell in, is completely different to the one you were just in 2 minutes ago. It turns out you have somehow defied the laws of physics and no-clipped into a pocket dimension. You feel vastly nauseous and dizzy. You start to dehydrate in a fraction of a second because of the excessive temperatures from the atmosphere, equivalent to being baked in an oven.")
    time.sleep(12)
    print("You are badly hurt... You have bruises on your chin, neck and your feet from the high-rise fall...")
    time.sleep(2)
    print("You were just hanging out with your two best friends at this fancy restaurant across town, Gus and John. You haven't eaten anything since last night. You simply asked the waiter where the bathroom was, and he lead you out back to an abandoned-looking area. When you entered inside with an eerie feeling, suddenly...")
    time.sleep(7)
    print("You had just slipped like a normal person would have if a floor were slippery or wet. This whole process happened in less than a millisecond. You cannot even recall how you fell, where you fell, and where you were during the fall...")
    time.sleep(a)
    print("At the speed of light, you plummeted into an unknown area... Desperate for food and water, and critically injured. With a great confusion and a little bit of curiosity you walk steadily and inspect the building which you have spawned in. What you see in your surroundings, are bright lights, never ending pathways, walls, and strange architecture.")
    time.sleep(8)
    print("You have so many thoughts, feelings and images going on inside your head in which you are completely sterilized.")
    time.sleep(2.6)
    print()
    s = "'I... I am so confused right now. What is going on? What is this place?'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(1.9)
    print()
    s = "'It... It's... freakishly disgusting...'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(3)
    print()
    print("Wherever you go, you barely find furniture or any objects, and when you do... They're all placed in such... random positions... very odd.")
    time.sleep(a)
    print("The carpets are stained in what smells like feces, urine and sweat. You notice mushrooms growing in all sorts of corners, and walls seemingly yellow soiled with filth. ")
    time.sleep(a)
    print()
    s = "'Why does this... kind of remind me of... an IKEA?'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(3)
    print()
    print("The white noise you hear from these bright lights, give you a terrible headache. You are so self-involved in confusion that you are unknowingly distracting yourself from your hunger and dehydration.")
    time.sleep(5)
    print("Walking further into this abyss, you spot... blood...?")
    time.sleep(3)
    print()
    s = "'Is this what I think it is? B-b-blood...?'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(1.4)
    print()
    s = "'There is something extremely suspicious about this place.'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(2)
    print()
    print("Squelchy and mushy sounds come from your shoes as you take steps. You find small little drawings on walls and furniture pointing arrows to different regions. Some drawings mimick doors on more yellow walls, which have 'EXIT' written on top of it. As fake as these drawings on the walls are... you hallucinate due to lack of food and water so you hopelessly walk into them, causing more damage to your body.")
    time.sleep(8)
    print()
    s = "'I... I d..don't think I can survive...'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(1.4)
    print()
    s = "'Just... just a little longer till I find something to eat...'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(2)
    print()
    print("So far, you feel like you have been here for days but it has only been 20 to 30 minutes. At a certain point... you find a door. The title of this door says... 'LEVEL 3: FUN ROOM!!!!' Although this time, this door is real. It's not like the fake ones you saw around the area...")
    time.sleep(6.7)
    print("As you look at the door, frightened, thinking to yourself... 'No... No... That's not possible... There can't be more additions to this place...")
    time.sleep(a)
    print("You hear footsteps... LOUD footsteps. The bright lights starts flickering, small dust particles fuming from inside the walls, the brown water and slop from inside the carpets start spraying upwards. You panic in an instant. You look back... and in the corner of a room displayed in the shadows... is an unknown entity, screeching and using its black twig-like legs to run after you as fast as it can.")
    time.sleep(12.4)
    print("The only thing running in your mind is to bolt away as quickly as possible. It is up to you whether you take the risk to go through that door or not...")
    time.sleep(a)
    print()
    print("What are you going to do? Decide. FAST. The monster is zooming towards you.")
    time.sleep(2)
    print()
    print("Path #1: Go through the 'FUN ROOM' door before the entity captures you.")
    time.sleep(2)
    print()
    print("Path #2: You don't go through that door, and you try your best to outrun the entity by finding a new place to hide in.")
    time.sleep(2)
    print()
    print("Path #3: Oh wait! A surprise! You see a little box a few rooms away, and it looks like a vent! You can confuse the monster by running around the hallway and going inside the vent!")
    time.sleep(2)
    print()
    firstPath = input("Quickly! You don't have much time to decide!! | 1 | 2 | 3 |: ") # right answer 3 venue will be cued at 4
    time.sleep(3)
    print()
    if firstPath == '1':
        print()
        path1()
    elif firstPath == '2':
        print()
        path2()
    elif firstPath == '3':
        print()
        path3()

def path1(): # first path
    print()
    print("You decide that it is best to go through the 'FUN ROOM' door... So without any more thinking you twist the door knob and you run inside the hallway of the 'FUN ROOM!!' as fast as you can. ")
    time.sleep(6)
    print("There is a large corridor with the colors of purple, orange, pink. Happy circus music is plays in the hallway. There are play areas, slides and waterparks everywhere but there doesn't seem to be a single child or adult. ")
    time.sleep(10)
    print("You cannot hear the entity anymore chasing behind you so that is a good sign... You think. As you walk more and more down to the waterpark you see that the pool water is producing toxic fumes, which is severely hazardous. ")
    time.sleep(10)
    print("You look more further and you spot again, red blood stains inside the pool and outside of the pool. You see some torn clothes, broken swimming toys, bathrobes and slippers around the place stained with blood too. ")
    time.sleep(10)
    print("You now know that this might be a way for a different type of entity to lure you in. In this dimension, you have to expect the worst. There is nothing that you cannot think of that will probably happen in this place. ")
    time.sleep(10)
    print("Just as you thought, this time... instead of one... you see several entites running after you in all sort of directions. These creature have clown costumes and big smiles, they have no eyes and they have the capability of running VERY fast.")
    time.sleep(12)
    print("Just as you are hopelessly sprinting away... the creatures quickly dive in front of you, and one of them mercilessly decapitates you.")
    time.sleep(6)
    print("As your head falls to the ground, the other entities begin to viciously devour your body...")
    time.sleep(a)
    print("The entities throw you into the 'water' causing your body to disintegrate.")
    time.sleep(a)
    print("You have officially been declared missing in the real world. No one, and no one ever can find your body again...")
    time.sleep(a)
    print()
    startGameAgain = input("Would you like to start the game from the beginning? (Y/N):  ")
    time.sleep(2)
    if startGameAgain == "y":
        intro()
    if startGameAgain == 'n':
        print("Thank you for playing this game. See you next time! ")
        time.sleep(2)

def path1_1(): # second path (option 3)
    print()
    print("So now, you decided to lure the entity into some room to kill it. You feel pretty confident in your idea so you leave the vending machine's location to go and find an applicable room to carry out the execution.")
    time.sleep(7)
    print("You try to find one which has some objects or furniture in them so you can use it to your advantage in several ways to defeat the creature. ")
    time.sleep(5)
    print("You found a nice room which has space enough for two giant elephants... And in this particular room, there is a whole office. A bunch of monitors, wires, measurement tapes, blueprints and paper. You can use the chair or monitors to throw, and wires and measurement tapes to either whip or choke the entity.")
    time.sleep(10)
    print("The papers and blueprints are quite useless so you have no meaning for them. ")
    time.sleep(a)
    print("You have your pocket knife in hand, and you have the strategy in your mind. You scream and screech out loud so that this monster will speed to your area...")
    time.sleep(5)
    print("You have now been screaming for the past 2 minutes and you hear nothing from the entity.")
    time.sleep(3)
    print()
    s = "'That's strange... Did I do something? Why is this creature not reacting to my noise?'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(2)
    print()
    print("You start to get curious about the situation, so you take your pocket knife along with you and some wires to keep in your pocket just in case... ")
    time.sleep(5)
    print("The entity is actually letting out it's own noise and it sounds like it's in pain...? ")
    time.sleep(3)
    print("You can use this to your advantage and go to the spot which the entity is in, to kill it. If... it's in a vulnerable state. ")
    time.sleep(a)
    print("The moment you go near the entity's area. It comes up behind you and with not even a second wasted... it sticks it's big thick claw in your chest.")
    time.sleep(5)
    print("It seems that it was the creature's plan to lure you instead of you luring 'it'... ")
    time.sleep(3)
    print("Your body is hanging off the claw... your blood starts to drip down to the carpet causing it to spread around to cause an extra blood stain. ")
    time.sleep(5)
    print()
    print("*THUD* your body drops to the floor. You bleed out slowly and painfully on the carpet until you die... You actually never had the chance of killing the entity in the first place. It knew everything...")
    time.sleep(a)
    startGameAgain = input("Would you like to start the game from the beginning? (Y/N):  ")
    time.sleep(2)
    if startGameAgain == "y":
        intro()
    if startGameAgain == 'n':
        print("Thank you for playing this game. See you next time! ")
    time.sleep(2)

def path1_2(): # second path (option 4)
    print()
    print("You decide to use the vent as a shortcut to go where the entity is, or atleast go near 'it'.")
    time.sleep(a)
    print("You walk away from the vending machine and find the vent again.")
    time.sleep(2)
    print("When you go inside the vent the pocket knife where you placed in your left pocket pricks your hip for every single second. It started off as a little tickle, but then it got progressively worse and now your left hip is bleeding out.")
    time.sleep(8)
    print("You make little noises of pain which the entity cannot seem to hear. But then once you reach the middle point of the vent, the pocket knife fully goes inside your hip and you scream out loud in an instant. The vent makes twice as more noise so the creature gets alarmed.")
    time.sleep(10)
    print("The entity starts charging towards the vent and lets out a huge scream which completely deafens your hearing. You cannot hear anything but you feel vibration in the vents. The creature is rushing inside and starts to gnaw at your legs. It gets violently angry as you start to cause more noise inside the vent.")
    time.sleep(11)
    print("At once, it chops off both of your legs so you make no noise again. Leaving you, stranded and no possibility to escape the vent ever again. ")
    time.sleep(6)
    print("Your hip and lower body bleed out slowly causing you to die a torturous death.")
    time.sleep(3)
    startGameAgain = input("Would you like to start the game from the beginning? (Y/N):  ")
    time.sleep(2)
    if startGameAgain == "y":
        intro()
    if startGameAgain == 'n':
        print("Thank you for playing this game. See you next time! ")
    time.sleep(2)

def path2(): #first path
    print()
    print("You decide that it can be a little bit more dangerous to go through that door. The lable might be a trick and you can die possibly immediately going in there. You turn to the opposite way and start to go in all sorts of places to avoid the entity. ")
    time.sleep(8)
    print("You run to different corridors, vents and hallways to escape the creature but it is still managing to catch up behind you. Due to your dehydration and hunger you have severe energy loss and your body and mind is barely functioning on a whim. Therefore, no matter how fast you run...")
    time.sleep(12)
    print("The entity is going to capture you, inevitably.")
    time.sleep(2)
    print("Suddenly, you faint to the ground from all of the pressure and intensity. This is it for you. Atleast you have died feeling no pain.")
    time.sleep(3)
    print("The creature executes you in a fraction of a second, leaving little to no evidence that you were ever killed. ")
    time.sleep(3)
    startGameAgain = input("Would you like to start the game from the beginning? (Y/N):  ")
    time.sleep(2)
    if startGameAgain == "y":
        intro()
    if startGameAgain == 'n':
        print("Thank you for playing this game. See you next time! ")
        time.sleep(2)

def path2_1(): # second path (option 5)
    print()
    print("You decided that you wanted to go look for sharp objects around the building to kill this thing. ")
    time.sleep(3)
    print("You leave the vending machine, and right away start to look for things to use. ")
    time.sleep(2.5)
    print("The pocket knife will not work so well against a creature the size of a lion so you have to find something else. ")
    time.sleep(a)
    print("You find a BIG office in some room on the west side of the hallway. You get to it and the only things you see are monitors, wires, chairs, and measurement tapes . You think to yourself that you can use these to your advantage. ")
    time.sleep(7)
    print("You go a little bit more further into the 'office room' and behind the wooden desk you see a toolbox in one of the shelves. You think to yourself, if this has some sharp things in them, I can use it!")
    time.sleep(6)
    print("You can use the wires and measurement tapes to strangle the entity. And you can also use them to whip it. You think that there is no use in monitors and chairs because it is too heavy to carry them and you might end up using all of your energy.")
    time.sleep(9)
    print("You look into a trash bin on the edge of the table and you find a wooden log. It is not too heavy to carry. You felt the edge of the wooden log and it is dull, meaning that it is not sharp at all. ")
    time.sleep(6.9)
    print()
    s = "'If there's some nails in this toolbox, I can attach them on the wooden log to make it deadly enough to kill the entity!'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(2)
    print("You find a lot of them in the toolbox... You attach as much of the nails as you can on the log.")
    time.sleep(3)
    print("After 10 minutes of sticking the nails into the log, the wooden bat is fatal enough to kill a whole army of those creatures. You start to feel confident and you continue to find the entity's position.")
    time.sleep(6)
    print()
    s = "You hit a right corner, and..."
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(2)
    print()
    print("The monster is looking right at you. You take your chance and you swing thrice at the entity when it seemingly screeches in defence, at your face making you stunned for a whole minute. ")
    time.sleep(6)
    print("The noise that this entity makes can be louder than two Tsar Bombs blowing up. Your earbuds instantly explode and you are left dead on the carpet. ")
    time.sleep(5)
    startGameAgain = input("Would you like to start the game from the beginning? (Y/N):  ")
    time.sleep(2)
    if startGameAgain == "y":
        intro()
    if startGameAgain == 'n':
        print("Thank you for playing this game. See you next time! ")
    time.sleep(2)

def path2_2(): # second path (option 2)
    print()
    print("You leave the vending machine's location but you were too curious about the 'FUN ROOM' to even worry about the food...")
    time.sleep(3)
    print()
    print("'Last time, I was at that door, the creature was coming after me, so I had to go inside that vent... Maybe if I go through that again... I can be in the same place where I was before and I'll get a better chance of finding that door again! ' ")
    time.sleep(8)
    print()
    print("You remember the pathway to the vent so you go back inside and now start slowly crawling across. There is still a risk that the entity went to that same position, on the opposite side of the vent.")
    time.sleep(6)
    print("You have some experience, so you know how to go through a vent silently. You peek out and you see the same old location again.")
    time.sleep(5)
    print("You have went across the vent and you are now in the same place you were in an hour ago. Your heart drops... In your peripheral vision, you notice that the creature is standing in that same place waiting for you to come out. It lured you back...")
    time.sleep(9)
    print("The entity starts rushing towards you, and in shock you are standing there completely paralyzed to the thought of dying a worthless death. ")
    time.sleep(6)
    print("You were not capable of moving... and the entity pounced and stabbed your body 51 times with it's claws. A bloody death was your consequence for this stupid idea. ")
    time.sleep(7)
    startGameAgain = input("Would you like to start the game from the beginning? (Y/N):  ")
    time.sleep(2)
    if startGameAgain == "y":
        intro()
    if startGameAgain == 'n':
        print("Thank you for playing this game. See you next time! ")
    time.sleep(2)

def path3(): #first path
    print()
    print("You have successfully made it into the vent to stay safe and you are waiting for the entity to lose interest and get off your back.")
    time.sleep(6)
    print("Squished inside the vent, you struggle to not cough as more and more dust enters through your nostrils and throat. You fill with fear and silently panic as the claustraphobia hits. Unfortunately, you do not have the power to do anything else in this state as of right now. ")
    time.sleep(12)
    print("Sitting there, in shock... As your mind and emotions are all over the place, and not quite being able to think straight, You still try your best to focus... strategizing and finding ways to get out of this building, let alone this vent without alarming that creature.")
    time.sleep(12)
    print("Your mind is fully composed with negative thoughts as you think to yourself, you are going to be stuck in this dimension for all eternity.")
    time.sleep(6)
    print("Soon enough, you return to a calm state. And then, pin-drop silence. The entity has left somewhile ago which supposes it has stopped 'caring' for now, but that doesn't mean it won't come back...")
    time.sleep(8)
    print("You are completely numb to your body requests. It is converting your body fat into energy, and there is quite of a possibility you might faint out of starvation or dehydration soon enough.")
    time.sleep(8)
    print("You temporarily get your brain signals back and regain some consciousness. Your mind is luckily functioning well enough, so you're getting some thoughts in-and-out your brain. If you do not act soon enough to get some human resources, your body will go into lockdown.")
    time.sleep(12)
    print("You peek out of the vent for a split second and detect the entity is about 20 meters away from your position. To your advantage, you can use this chance to depart from the vent to look for some food and water.")
    time.sleep(11)
    print("If you do not want to risk it, you can stay inside the vent for a little bit longer until the entity renounces from your area completely. ")
    time.sleep(6)
    print()
    firstChoice = input("Would you like to stay in the vent? | 1 |, or will you leave and look for human resources? | 2 |. You decide: ")
    time.sleep(3) # right answer 2
    if firstChoice == '1':
        path4_1()
    elif firstChoice == '2':
        path4()

def path4_1(): #first choice
    print()
    print("You were too scared to go out of the vent because you did not want to risk your life. Your plan is simple. You stay in the vent for a little bit more longer until the entity starts walking to a different direction, thus giving you time to leave the vent! ")
    time.sleep(11)
    print("It has been a total of 23 minutes and the entity has changed it's mind and is walking towards another direction. ")
    time.sleep(6)
    print("Now, since you have enough time to get out of the vent to go look for food, you get... stuck.")
    time.sleep(a)
    print()
    s = "'WAIT, A-AM I... AM I STUCK?'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    print("You have been in the same position, in the vent for a little bit too long and now you are not able to move...")
    time.sleep(a)
    print("A couple of years ago, you were diagnosed with severe claustraphobia from a doctor in New York, named Dr. James Hamilton. Since then, you have not been in one single tight space in your life, because you would fear that some horrible consequence might inflict upon you. ")
    time.sleep(7)
    print()
    print("But now... you are in a vent that is is as wide as your leg, and as long as 2 chairs stacked on top of each other. You had no other choice other to go in, otherwise you would have died a worse death with that monster... ")
    time.sleep(8)
    print("Your mind fills up with anxiety and pressure from your heart. You start to hyperventilate and your brain triggers an escaping response. But in this case, you cannot really escape. You start to move around the vent and cry in discomfort as your claustraphobia hits another level.  ")
    time.sleep(12)
    print("Just as the creature was about to leave, the sound waves from the vent traveled straight through the entity's ears. This caused it to riot and and go crazy. ")
    time.sleep(6)
    print("The creature immediately goes inside the vent to try and kill you. As you notice this, you produce even more noise inside the vent hoping that the entity runs away because of the commotion. Instead...")
    time.sleep(8)
    print("The entity managed to go even more deeper inside the vent, and suddenly grabs your legs and pulls them out of their sockets effortlessly. The creature instantly breaks your legs, and destroys your lower limbs, making it impossible for you to neither cause any noise, or escape.")
    time.sleep(12)
    print("The monster takes you by the by the head and pulls it towards itself causing it to come right off. You have been decapitated. ")
    time.sleep(5)
    startGameAgain = input("Would you like to start the game from the beginning? (Y/N):  ")
    time.sleep(2)
    if startGameAgain == "y":
        intro()
    if startGameAgain == 'n':
        print("Thank you for playing this game. See you next time! ")
        time.sleep(2)

def path4(): #right answer 2, first choice add time sleeps first FIRST!
    print()
    print("You take the sudden action to crawl to the opposite side of the vent and evacuate as quietly as possible to another room so that the entity doesn't detain you... ")
    time.sleep(6)
    print("You have successfully made it into a room without any loud noise. You now walk around, slowly... fictionally hoping you might run into a dining hall of some sort...")
    time.sleep(6)
    print("By God's grace, you luckily find a small vending machine two blocks across the room you are in... You think to yourself, 'If I can get there safely, I can store some food and survive for a little bit longer.'")
    time.sleep(9)
    print("While trying to find a way to effectively pass through to the vending machine, You think...")
    time.sleep(a)
    print()
    s = "'That one door... It was called.... The 'FUN ROOM' wasn't it? Yeah... Fuck... I forgot where that was again...'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    print("Remember? You were in panic, so you completely forgot where that door was. You were too focused on escaping, and running around the building from the entity , you forgot all about it.")
    time.sleep(6)
    print("You stop in your tracks, and you find some type of closet...?")
    time.sleep(2)
    print()
    s = "'Wait, what's this...?'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    s = "'Oh yeah. It's just one of those objects placed randomly here...'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    print("You don't think much of it and you proceed to move on... ")
    print("The thought of still trying to find the 'FUN ROOM's door is not getting out of your head...")
    print()
    s = "'Should I go find that door again? If that monster isn't around that area... I can find time to look for that door. Maybe that place might be a little more safer... After all, it did say 'FUN ROOM!!!!!' on it...'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    s = "'Or should I still keep on going to the vending machine...?'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    print("You do not know what you want to do and more and more ideas keep on coming in... You came to notice that the entity makes noises every 5 minutes... In fact, it is very sensitive to noise too...")
    time.sleep(6)
    print("You stick your back against a wall and strategize, once again.")
    time.sleep(2)
    print()
    s = "'Wait... is this... is this my wallet?!?! Oh my God!"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    print("While you were against the wall, you felt your wallet in your left pocket from behind. That is where you always keep it. You suddenly get an idea. Inside that wallet, is a not so very small pocket knife that you keep on at all times incase of emergencies.")
    time.sleep(10)
    print()
    s = "'I think I have an idea...'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    s = "'What if I can use this pocket knife to stab this entity to death by luring it to a certain room with my voice? Yes... That sounds look like a good idea.'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    print("While you are thinking of ways to survive and escape, every 2 to 3 minutes you hear the entity screaming and crying out constantly... Almost like it's in pain...")
    time.sleep(6)
    print("Whenever the creature moves around, the accomodation moves and vibrates at a high frequenecy. This means that the entity is not stationary, and that it is in motion.")
    time.sleep(7)
    print("But... the entity is not moving at all... because you cannot hear or feel any vibration frequencies.")
    time.sleep(a)
    print()
    s = "'Wait, does this really mean that I can actually kill this creature...??? Alright! Although, I need to see the entity's situation to decide do this or not.' You think."
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    print("You start to get curious and think to yourself if it is a good idea to go to the entity's position, and see if it is actually in a vulnerable state or not.")
    time.sleep(6)
    print("This can be an extraordinary opportunity to execute the entity and find a way to escape the building. But in order to do this, you must sacrifice going to the vending machine and finding the door to the 'FUN ROOM!!!!' room to go take a look at the entity's condition to be able to murder it.")
    time.sleep(11)
    print("If you would want to kill this creature... you can either lure it into a room, maybe make some type of trap and killing it there with your pocket knife, directly use the vent as a shortcut to the entity's position to carry out the assassination there itself,")
    time.sleep(10)
    print("or you can search different types of locations in the building for sharp objects to bring with you so you have a higher chance of killing it.")
    time.sleep(7)
    print("You also just walked past a closet, and there might be many more things upon discovery in there which you can use. ")
    time.sleep(a)
    print("You decide, what you think is the right thing to do... and think carefully or else you will sacrifice some things which you shall regret soon enough.")
    time.sleep(7)
    print()
    print("You now have five paths. You have to really think it out because you have the time. What will it be? ")
    time.sleep(2)
    print()
    print("Path #1: Continue the path down to the vending machine, and gather food and water to stay alive. ")
    time.sleep(2)
    print()
    print("Path #2: Risk going to the vending machine, and try your best to find the door that leads to the 'FUN ROOM'")
    time.sleep(2)
    print()
    print("Path #3: Lure the entity to a certain room, make some sort of trap and kill it using your pocket knife. ")
    time.sleep(2)
    print()
    print("Path #4: Use the vent as a shortcut to go the same place where the entity is and execute it right there on the spot. ")
    time.sleep(2)
    print()
    print("Path #5: Try to find different types of sharp objects to bring with you and find another path to it's position.")
    time.sleep(2)
    print()
    secondPath = input("Which path will you choose? | 1 | 2 | 3 | 4 | 5 |: ")
    time.sleep(2) # right answer 1
    if secondPath == '1':
        path5()
    if secondPath == '2':
        path2_2()
    elif secondPath == '3':
        path1_1()
    elif secondPath == '4':
        path1_2()
    elif secondPath == '5':
        path2_1()

def path5(): # answer 1 from second path, make sure to put time sleep on all other options too
    print()
    print("Good thinking. Best to be safe.")
    time.sleep(2)
    print("You make your way to the vending machine, quietly without the entity noticing... around 10 minutes go by as that is the time it takes you to arrive to it. You notice bunch of cans having the name 'Almond Water' taped on them lying around, surrounding the vending machine. As you enter that field, there are progressively more stains on the carpet around the location. You take a look inside, and you see plenty of the same packets on each row... sesame seeds, sunflower seeds, and for some reason... Jelly? all placed down inside.")
    time.sleep(12)
    print("As you gaze in shock of relief at the vending machine, drooling all over your clothes and caught in a trance of a food fever. You are way too damn hungry to even care what you're gonna eat, you just want to put something in your mouth. You notice on the vending machine... it does not have any card reader, so you take out your wallet in distress hoping that you have some remaining cash on you. You suddenly drop your pocket knife making it richocet off the wall, causing an echo... making the sound waves travel to a mile away. You hear the monster squealing one more time, but this time louder... A strike of nervouseness and fear goes down your spine in a split of a second...")
    time.sleep(14)
    print("You lift up your pocket knife in suspense as your hands grip on to the grimy and soggy carpet. You stick your pocket knife back into your left back pocket. ")
    time.sleep(6)
    print("In one deep breath, you lift your head up to notice that there is not a single coin collector either. This means, that it is absolutely impossible to get any resources from this specific vending machine. ")
    time.sleep(8)
    print("Your mind starts to fill up with panic and frustration knowing that food is right in front of you, yet you cannot eat. You immediately start getting exasperated.")
    time.sleep(7)
    print("In a desperate eagerness for food, you feel like breaking the glass. You cannot use your pocket knife because it is sensitive and can get dull very quickly. You touch and feel the glass and come to know that it is 'Bullet-resisting glass.' Meaning that it is significantly hard to break through it. Your mind is still being blinded by the thought of food. Because of this, you run around... like a headless chicken, trying to find a sharp object somewhere, to break it. ")
    time.sleep(10)
    print("You stop in your tracks and your senses kick in... you promptly realize that breaking the glass will cause more and more noise for the entity to understand which area you are in and will instantly come and hunt you down. ")
    time.sleep(9)
    print("You keep on trying to make up different ways on how to get food from the vending machine but you get a conception knowing that the only other thing in this situation is leaving it, and go through with the plan of killing the entity. ")
    time.sleep(8)
    print("You stand there, stare at the food... you cannot take this hunger anymore... out of nowhere, you start to prick at the door with your pocket knife without caring for the consequences. The noises from the knife is so loud, that the echo travels to other areas which gets progressively louder. ")
    time.sleep(10)
    print("You calm down, to stop and think... and now finally realize that the creature is definitely in trouble.")
    time.sleep(a)
    print()
    s = "'There's no way that this creature isn't already running after me after all this nuisance. It must be hurt or something... Wait, can I use this to my advantage?'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    print("You get a sudden gasp of excitement. You now have a chance of either killing this thing or keep on trying to break the glass of the vending machine with your knife...")
    time.sleep(5)
    print()
    importantPath = input("Do you want to leave the vending machine's location and go to assassinate the entity, | 1 |, or would you like to continue trying to break the glass to get some food before you die out of starvation, | 2 |. You decide:  ")
    time.sleep(6)
    if importantPath == '1':
        path4_2()
    if importantPath == '2':
        path4_3()

def path4_3(): # wrong answer(2)
    print()
    print("You cannot risk your hunger anymore. You feel like you are going to pass out any minute now. You continue to try to break the glass as quietly as you can so you don't get noticed by the creature. ")
    time.sleep(7)
    print("Of course this is not possible so you have no other choice than to do break it as hard as you can. YOur plan is to break the glass as hard and quickly as possible, get some food and run back to the vent so that the entity doesn't capture you in time ")
    time.sleep(9)
    print("You take the pocket knife and you stab it really hard at the glass around three times and then suddenly... it breaks. You look at the knife in shock as you realize you might just be doomed.")
    time.sleep(6)
    print("The sound was as loud as a pan hitting a kitchen floor. Behind you, comes the creature zooming at you in maximum speed, and you have no way of defending yourself. You have no other choice than just to accept death. ")
    time.sleep(8)
    print("The monster decimates you to the floor causing your insides to squish out. Oh, the gore...")
    time.sleep(a)
    startGameAgain = input("Would you like to start the game from the beginning? (Y/N):  ")
    time.sleep(2)
    if startGameAgain == "y":
        intro()
    if startGameAgain == 'n':
        print("Thank you for playing this game. See you next time! ")
        time.sleep(2)

def path4_2():  # right answer 1
    print()
    print("You swallow your heart back into your chest, and you take the action to go and carry out the assassination. You had to leave your pocket knife behind because it was well-near broken. ")
    time.sleep(7)
    print("Last time, you had several options for which ways you can eliminate the entity. Now, you will first need to find a sharp object to replace the pocket knife. ")
    time.sleep(6)
    print("With no other option you silently walk away from the vending machine with emotions mixed up of sadness and frustration. As you come out of it's area..." )
    time.sleep(5)
    print()
    print("Platforms, rooms, and the whole building... out of nowhere... changed? PLOTTWIST???")
    time.sleep(3)
    print()
    s = "'Wait, what is this...? Can I not kill that monster anymore? Did all of my plans just go to waste? What's going on? W- Why am I in a different place?!?!?'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    print("There are new structures and new type of furniture and objects everywhere. The wall color is completely different and not one single carpet on the floor. The floor is made out of concrete this time.  You can still hear the entity, but this time from another further distance. You start to think about it, and you realize that you might have accidentally teleported into another region in this building just like how you teleported here in the first place. ")
    time.sleep(12)
    print()
    s = "'Oh.. I think I'm just in a different base. I'm sure it's possible to kill this thing...'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    print("The formation and design of this certain part of the building is completely unalike and mismatched. The walls have a slight grey tone to them, and the concrete floor seems to get cold in some instances. This time, there are no bright lights in the corridors anymore. Meaning that there isn't that extremely annoying sound frequency that impales your head.")
    time.sleep(8)
    print("There are pipes everywhere, and locked iron doors. Some walls have a magnificent architecture to them which make it quite enjoyable to look at.")
    time.sleep(5)
    print("Due to the pipes, there is a slight breeze which is caused by the air conditioner across the hallway. No more odd smells, wet dirty carpets, terribly hot atmoshphere and the unbearable noise and brightness from the lights...")
    time.sleep(8)
    print()
    s = "'Wait, I think this is some sort of storage room or basement that I must have no-clipped into... I think I might be able to use this place to finally take a break... I don't even feel like doing anything right now...'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    print("You are still so very hungry and the only thing that's on your mind is the regretfullness of not trying harder to get something to eat at that vending machine. ")
    time.sleep(5)
    print("But at the same time, you knew that that was the right and only choice left. Otherwise, if you tried more harder to break the glass, the entity could still have been able to kill you, and you would not have had any way of defending yourself, because your knife wouldn't have worked out for you. ")
    time.sleep(8)
    print()
    s = "'I've been here for some time, I still need to escape... It's time to go now.'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    print("You try to find ways to exit this 'basement' building, as you call it... ")
    time.sleep(2)
    print("Your main goal still stands... and that is to assassinate the entity. ")
    time.sleep(2)
    print("You find a stairset to a door... which leads back to the yellow region. You go through the door and proceed to walk around the hall with the mission of finding a sharp object to kill this creature.. You run into that little closet which you saw an hour ago. With no hesitation, you look inside desperate to find a sharp object. ")
    time.sleep(10)
    print("Not finding anything on the right side, you turn to the left side of the closet and...")
    time.sleep(3)
    print()
    s = "That's strange..."
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(2)
    print()
    s = "'Hold on... what the fuck...?! Is... Is this... Is this my pocket knife? "
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(2)
    print()
    print("You spot your pocket knife looking completely brand new and thoroughly sharpened again. You abandoned it last time, so how... how is it...")
    time.sleep(a)
    print()
    print("The knife is just sitting there, waiting to be used. Having the only thing on your mind, vengeance... without any hesitation, and no question on how did it appear there all of a sudden, you directly take the pocket knife in this closet to defeat the entity. ")
    time.sleep(7)
    print()
    s = "Little did you know..."
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(2)
    print()
    print("Out of nowhere, the ground around you starts blowing up... everything around you starts violently shaking and collapsing. You feel like the floor is going to crumble down beneath you . ")
    time.sleep(6)
    print()
    print("The dust from the walls start fuming out, and the carpet produces more grimy water as the atmosphere starts to get intensively cold. The dark lights get instantly bright and loud.")
    print()
    time.sleep(6)
    s = "The whole pocket-dimension is starting to fall apart..."
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(2)
    print("Blinded by rage, you run as fast as you can with the knife in hand to the entity's location. ")
    time.sleep(a)
    print("You look straight at the creature who is standing exactly 23 meters away from you. The entity has no facial features, and looks like several sticks dipped in ink, clunked up together.")
    time.sleep(6)
    print("2 seconds later, the entity starts charging towards you in maximum speed.")
    time.sleep(a)
    print("You come to realize that this whole operation was a trap all along... This monster wanted you to think that it was 'injured' or in trouble so that you would come to it's territory...")
    time.sleep(6)
    print("In order to get you closer to itself, it fixed your pocket knife so you would take it and come to the same area to carry out the massacre. Turns out, the entity... lured you instead.")
    time.sleep(6)
    print("It was watching everything. It knew that you left your only weapon and knew your goal had since been to search for a sharp object to replace it... ")
    time.sleep(5)
    print()
    print("You start bolting the fastest you can and at this point the creature is catching up to you. ")
    time.sleep(a)
    print("You try your best to outrun the entity but it still manages to stay on your back. To make things worse, the floors are crumbling and disintegrating at the same time. ")
    time.sleep(6)
    print("You look into the distance and you see a small little wooden door displaying 'EXIT' on top of it... can this be the way back home?")
    time.sleep(5)
    print("The entity is flashing towards you with a 5 meter length distance between. You try to run at the speed of light toward the EXIT not caring about the collapsing floor.")
    time.sleep(7)
    print("Speeding towards the exit is the best way possible to avoid any trouble. But you can still use your now 'upgraded' pocket knife to stab the entity to death, saving time to go through the EXIT. ")
    time.sleep(7)
    print()
    print("What's your choice gonna be? Quickly decide! The pocket dimension is destroying. ")
    time.sleep(2)
    print()
    print("Path #1: Stab the entity to death first, and run to the exit after so that the creature won't have a chance to capture you.")
    time.sleep(2)
    print()
    print("Path #2: Do not risk your life, and charge to the EXIT as fast as possible.")
    time.sleep(2)
    print()
    thirdPath = input("What are you going to do? This is your final decision. Choose between the two: | 1 | 2 |:  ")
    if thirdPath == '1':
        path3_1()
    elif thirdPath == '2':
        path3_2()

def path3_1(): # final wrong
    print()
    print("You stop for a second so that the creature catches up to you, and then with a sudden stroke you stick the pocket knife in the center point of it's chest causing it to whimper out loud.")
    time.sleep(5)
    print("You have successfully bought more time as you flee to the exit in excitement!")
    time.sleep(2)
    print()
    s = "*BOOM*"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(2)
    print()
    print("The floor breaks apart beneath you and you fall into it. You trap both of your legs and your arm inside the floor as it crushes together in a second. You scream in pain as three of your limbs completely get destroyed. The entity dies out of losing blood... But you still have no way of going to the exit...")
    time.sleep(12)
    print("You look at the EXIT as you slowly and painfully get crushed and swallowed into the floor. You have died even while having the exit only a meter away from you.")
    time.sleep(5)
    startGameAgain = input("Would you like to start the game from the beginning? (Y/N):  ")
    time.sleep(2)
    if startGameAgain == "y":
        intro()
    if startGameAgain == 'n':
        print("Thank you for playing this game. See you next time! ")
        time.sleep(2)

def path3_2(): #final and right path
    print()
    print("As you run to the exit, the floor is crumbling beneath you but you have enough time to jump and dive in through the door... You have been dreaming of this moment. ")
    time.sleep(5)
    print("The entity suddenly falls through one of the cracks and gets swallowed by the floor. 'It' lets out a huge scream as the building starts collapsing even more. ")
    time.sleep(5)
    print("You have successfully, and finally made it to the platform of the door. Looking back at the dimension, falling apart... You go through the door with extreme happiness, and...")
    time.sleep(6)
    print()
    s = "'H...H-Huh? W..Why am I here... again?"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(2)
    s = "'WAIT... NO... NO... N-'"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(1)
    print("Everything around you looks bright yellow, cold, empty and liverish... The atmosphere is oddly hot, and suffocating...")
    time.sleep(3)
    print("You abruptly fall... face plant on a beige nasty, wet carpet. The moist of the rug cancelles out the huge noise. The place in which you have fell in, is completely different to the one you were just in 2 minutes ago.")
    time.sleep(6)
    print("It turns out you have somehow defied the laws of physics and no-clipped into a pocket dimension. You feel vastly nauseous and dizzy. You start to dehydrate in a fractio-")
    time.sleep(a)
    print()
    s = "There was no escape... there was no exit... there was nothing you could have done..."
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(2)
    print()
    s = "The whole thing is a never-ending loop that no matter how many times you try to escape... it returns you right back."
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(2)
    print()
    s = "What is there to do...?"
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    print()
    print()
    print("Thank you, dear Player... for playing. I hope you have enjoyed this adventure/playthrough. ")
    time.sleep(3)
    print()
    print("Best Regards,")
    time.sleep(1)
    print()
    print("Satvik Velpula")
    time.sleep(2)













print()
print()
print("      _______________________")
print("     |                       |")
print("     |                       |")
print("     |     The Backrooms     |")
print("     |                       |")
print("     |                       |")
print("      _______________________")
print()
time.sleep(2)
s = "Wait, wha... what.. what happened to me? Where am I? Gus? John? Where are you guys? "
for character in s:
    sys.stdout.write(character)
    sys.stdout.flush()
    time.sleep(b)
time.sleep(2)
s = "GUYS?!?!?"
for character in s:
    sys.stdout.write(character)
    sys.stdout.flush()
    time.sleep(b)
time.sleep(1.7)
s = " What the hell is this? I was just hanging out with John and Gus like two seconds ago. "
for character in s:
    sys.stdout.write(character)
    sys.stdout.flush()
    time.sleep(b)
time.sleep(1.5)
print()

s = "I must have glitched somewhere. This can't be right. I know it. There's no way this is a dream. "
for character in s:
    sys.stdout.write(character)
    sys.stdout.flush()
    time.sleep(b)
time.sleep(1.6)
startGame = input("Hello there, would you like to start the game? [PSA: Use the white drag-cursor to read through text.] (Y/N):  ")
if startGame == 'n' or startGame == 'N':
    print("Alright, your choice... But don't think you're gonna escape from here... You want to go back home, don't you? Go head and exit this terminal, and press that little green button to run this code again...")
    time.sleep(1)
elif startGame == 'y' or startGame == 'Y':
    print("Good choice. Are you ready? Let's start now.")
    intro()

